export const AddBase64InImg = (img) => {
    return `data:image/jpeg;base64,${img}`
}

export const ExtendedCategories = {
    'jewellery': 'Jewellery',
    'hair-accessories': 'Hair Accessories',
    'scraves-shawl': 'Scraves/ Shawl',
    'watches': 'Watches',
    'glasses': 'Glasses',
    'other': 'Other',
    'ties': 'Ties',
    'belts': 'Belts',
    'hats': 'Hats',
    'masks': 'Masks',
    'eye-masks': 'Eye Masks',
    'view-all': 'View All',
    'blouse': 'Blouse',
    'skirts': 'Skirts',
    'trousers': 'Trousers',
    'knitwear': 'Knitwear',
    'jacket': 'Jacket',
    'lingerie': 'Lingerie',
    'homewear': 'Homewear',
    'sportwear': 'Sportwear',
    'swimwear': 'Swimwear',
    'socks': 'Socks',
    'shoes': 'Shoes',
    'underwear': 'Underwear',
    'couple-clothing': 'Couple Clothing',
    'post-cards': 'Post Cards',
    'stickers': 'Stickers',
    'tapes': 'Tapes',
    'postage': 'Postage',
    'envelopes-writing-papers': 'Envelopes/ Writing Papers',
    'red-pockets-red-banners': 'Red Pockets/ Red Banners',
    'paper-boxes-package-boxes': 'Paper Boxes/ Package Boxes',
    'notebooks': 'Notebooks',
    'albums': 'Albums',
    'calenders': 'Calenders',
    'pens': 'Pens',
    'pen-cases': 'Pen Cases/ Pen Bags',
    'pen-stands': 'Pen Stands/ Pen Vases',
    'folders': 'Folders',
    'stamps': 'Stamps/ Stamp Pads',
    'bookmarks': 'Bookmarks',
    'slipcases': 'Slipcases',
    'furnish-and-decorate': 'Furnish and Decorate',
    'candles-scents': 'Candles/ scents',
    'plants': 'Plants/ Potted Plants',
    'vases-china': 'Vases/ China',
    'posters': 'Posters/ Paintings',
    'portrait-customisation': 'Portrait Customisation',
    'wallpapers': 'Wall Stickers/ Wallpapers',
    'photo-frames': 'Painting Frames/ Photo Frames',
    'dolls-figures': 'Dolls/ Figures',
    'storage-sets': 'Storage Sets',
    'furniture-beddings': 'Furniture/ Beddings',
    'cups': 'Cups',
    'cutleries': 'Cutleries',
    'kitchenware': 'Kitchenware',
    'beverage': 'Beverage',
    'bakeries': 'Bakeries',
    'snacks': 'Snacks',
    'seasonings': 'Seasonings',
    'pet-supplies': 'Pet Supplies',
    'gear': 'Sport Equipment/ Gear',
    'technology': 'Technology',
    'DIY-materials': 'DIY Materials',
    'clutches': 'Clutches',
    'crossbody-bags': 'Crossbody Bags',
    'shoulder-bags': 'Shoulder Bags',
    'cosmetic-bag': 'Cosmetic Bag',
    'wallet': 'Wallet',
    'rucksacks': 'Rucksacks',
    'messenger-bags': 'Messenger Bags',
    'briefcases': 'Briefcases',
    'laptop-pouch': 'Laptop Pouch',
    'travel-bags': 'Travel Bags/ Suitcases',
    'gadget-bags': 'Gadget Bags',
    'cosmetic-products': 'Cosmetic Products',
    'skincare-products': 'Skincare Products',
    'body-products': 'Body Products',
    'hair-products': 'Hair Products',
    'beauty-tools': 'Beauty Tools',
    'nail-products': 'Nail Products',
    'fragrance': 'Fragrance',
    'beard-products': 'Beard Products',
    'accessories': 'Accessories',
    'candles-aromatherapy': 'Candles/ Aromatherapy',
    'planting': 'Planting',
    'gourmet': 'Gourmet',
    'illustration': 'Illustration/ Painting/ Calligraphy',
    'leathercrafting': 'Leathercrafting',
    'carpentry': 'Carpentry',
    'pottery': 'Pottery',
    'knitting': 'Knitting',
    'outdoor-activities': 'Outdoor Activities',
    'indoor-activities': 'Indoor Activities',
    'casual-seminar': 'Casual Seminar'
};


export const LabelOptions = (lang) => [
    { id: 'gifts', text: lang === 'en' ? 'Gifts' : '禮物' },
    {
        id: 'recommendedgifts',
        text: lang === 'en' ? 'Recommended Gifts' : '推薦禮物',
    },
    { id: 'customgifts', text: lang === 'en' ? 'Custom Gifts' : '訂做禮物' },
    { id: 'diygifts', text: lang === 'en' ? 'DIY Gifts' : 'DIY禮物' },
    {
        id: 'birthdaygifts',
        text: lang === 'en' ? 'Birthday Presents' : '生日禮物',
    },
    {
        id: 'valentinesgifts',
        text: lang === 'en' ? 'Valentines Gifts' : '情人節禮物',
    },
    { id: 'couplegifts', text: lang === 'en' ? 'Couples Gifts' : '情侶禮物' },
    {
        id: 'anniversarygifts',
        text: lang === 'en' ? 'Anniversary Gifts' : '紀念禮物',
    },
    {
        id: 'mothersdaygifts',
        text: lang === 'en' ? 'Mother’s Day Gifts' : '母親節禮物',
    },
    {
        id: 'fathersdaygifts',
        text: lang === 'en' ? 'Father’s Day Gifts' : '父親節禮物',
    },
    {
        id: 'girlfriendgifts',
        text: lang === 'en' ? 'Girlfriend Gifts' : '女朋友禮物',
    },
    {
        id: 'boyfriendgifts',
        text: lang === 'en' ? 'Boyfriend Gifts' : '男朋友禮物',
    },
    { id: 'giftsexchange', text: lang === 'en' ? 'Gifts Exchange' : '交換禮物' },
    {
        id: 'graduationgifts',
        text: lang === 'en' ? 'Graduation Gifts' : '畢業禮物',
    },
    { id: 'weddinggifts', text: lang === 'en' ? 'Wedding Gifts' : '結婚禮物' },
    { id: 'bridalgifts', text: lang === 'en' ? 'Bridal Gifts' : '姊妹禮物' },
    {
        id: 'christmasgifts',
        text: lang === 'en' ? 'Christmas Gifts' : '聖誕禮物',
    },
    {
        id: 'heartfeltgifts',
        text: lang === 'en' ? 'Heartfelt Gifts' : '心意禮物',
    },
    { id: 'bestiegifts', text: lang === 'en' ? 'Bestie Gifts' : '閨蜜禮物' },
    { id: 'coupleoutfits', text: lang === 'en' ? 'Couple Outfits' : '情侶裝' },
    {
        id: 'parentchildoutfit',
        text: lang === 'en' ? 'Parent Child Outfit' : '親子裝',
    },
    { id: 'hipsterlook', text: lang === 'en' ? 'Hipster Look' : '文青' },
    { id: 'trending', text: lang === 'en' ? 'Trending' : '流行' },
    { id: 'minimalstyle', text: lang === 'en' ? 'Minimal Style' : '簡約' },
    { id: 'kawai', text: lang === 'en' ? 'Kawai' : '可愛' },
    { id: 'soothing', text: lang === 'en' ? 'Soothing' : '治癒' },
    { id: 'romantic', text: lang === 'en' ? 'Romantic' : '浪漫' },
    { id: 'vintage', text: lang === 'en' ? 'Vintage' : '復古' },
    { id: 'stylish', text: lang === 'en' ? 'Stylish' : '型格' },
    { id: 'animals', text: lang === 'en' ? 'Animals' : '動物' },
    { id: 'forestry', text: lang === 'en' ? 'Forestry' : '森林林系' },
    { id: 'japanese', text: lang === 'en' ? 'Japanese' : '日系' },
    { id: 'finesilver', text: lang === 'en' ? 'Fine Silver' : '純銀' },
    { id: 'rosegold', text: lang === 'en' ? 'Rosegold' : '玫瑰金' },
    { id: 'dyedwhite', text: lang === 'en' ? 'Dyed white' : '顯白' },
    { id: 'slimcut', text: lang === 'en' ? 'Slim Cut' : '顯瘦' },
    { id: 'handmadegoods', text: lang === 'en' ? 'Handmade goods' : '手作小物' },
    { id: 'handicrafts', text: lang === 'en' ? 'Handicrafts' : '手工製作' },
    { id: 'handpainted', text: lang === 'en' ? 'Hand Painted' : '手繪' },
    {
        id: 'environmentalfriendly',
        text: lang === 'en' ? 'Environmental Friendly' : '環保',
    },
    { id: 'workshop', text: lang === 'en' ? 'Workshop' : '工作坊' },
    {
        id: 'extracurricularactivities',
        text: lang === 'en' ? 'Extracurricular Activities' : '興趣班',
    },
    { id: 'weekendspots', text: lang === 'en' ? 'Weekend Spots' : '週末好去處' },
    {
        id: 'parentchildspots',
        text: lang === 'en' ? 'Parent Child Spots' : '親子好去處',
    },
    { id: 'couplespots', text: lang === 'en' ? 'Couples Spots' : '情侶好去處' },
    { id: 'datingspots', text: lang === 'en' ? 'Dating Spots' : '拍拖好去處' },
    {
        id: 'weekendmarkets',
        text: lang === 'en' ? 'Weekend Markets' : '週末市集',
    },
    {
        id: 'hongkongdesigns',
        text: lang === 'en' ? 'Hong Kong Designs' : '香港設計',
    },
    {
        id: 'hongkongbrands',
        text: lang === 'en' ? 'Hong Kong Brands' : '香港品牌',
    },
    {
        id: 'originaldesign',
        text: lang === 'en' ? 'Original Design' : '原創設計',
    },
];